mongodb
andrii-svyshch/nodejs-homework-rest-api pull request #2
Opened 2022-01-30 18:12 UTC by andrii-svyshch

Перевір будь ласка hw03

2022-01-31 21:00 UTC, KirillKulakow commented on routes/api/contacts.js
> +    if (error.message.includes("Cast to ObjectId failed")) {
лучше так не делать - делай проверку перед вызовом к базе данных
mongoose.Types.ObjectId.isValid

2022-01-31 21:01 UTC, KirillKulakow commented on routes/api/contacts.js
> +    if (error.message.includes("validation failed")) {
зачем тебе здесь обработка валидации mongoose если у тебя есть валидация JOI
масло масляное

2022-01-31 21:02 UTC, KirillKulakow commented on routes/api/contacts.js
> +    const result = await Contact.findByIdAndDelete(id);
добавить валидацию ид
mongoose.Types.ObjectId.isValid

2022-01-31 21:02 UTC, KirillKulakow commented on routes/api/contacts.js
>      const { id } = req.params;
валидация ид

2022-01-31 21:03 UTC, KirillKulakow commented on routes/api/contacts.js
> +    const { id } = req.params;
валидация ид

2022-01-31 21:03 UTC, KirillKulakow requested changes
need fix

2022-02-01 21:06 UTC, andrii-svyshch commented on routes/api/contacts.js
> +    if (error.message.includes("Cast to ObjectId failed")) {
так Богдан показував на заняттях)

2022-02-01 21:06 UTC, andrii-svyshch commented on routes/api/contacts.js
> +    if (error.message.includes("validation failed")) {
тут теж можу посилатися на Богдана

2022-02-01 22:14 UTC, KirillKulakow approved these changes

2022-02-02 20:08 UTC, merged