avatars
andrii-svyshch/nodejs-homework-rest-api pull request #4
Opened 2022-02-14 17:23 UTC by andrii-svyshch

Привіт. Перевір будь ласка

2022-02-14 19:12 UTC, KirillKulakow commented on routes/api/auth.js
> +    const avatarURL = gravatar.url(email);
нужно добавить опцию протокола в данный метод для выдачи полной ссылки

2022-02-14 19:13 UTC, KirillKulakow commented on routes/api/users.js
> +      const avatarURL = path.join("avatars", newFileName);
попробуй сделать данную ссылку в варианте http:localhost:3000/public/avatars/image.jpg
чтобы при вставке данной ссылки в браузере тебе отдалась данная картинка

2022-02-14 19:14 UTC, KirillKulakow requested changes
Need fix

2022-02-20 13:50 UTC, andrii-svyshch commented on routes/api/users.js
> +      const avatarURL = path.join("avatars", newFileName);
відкоригував, але якщо в посиланні є /public/ то  видає помилку

2022-02-20 15:11 UTC, KirillKulakow commented on routes/api/auth.js
> +    const avatarURL = path.join(`${req.protocol}` + ":", gravatar.url(email));
https://github.com/emerleite/node-gravatar
вот документация, не придумывай велосипед)

2022-02-20 15:12 UTC, KirillKulakow commented on routes/api/users.js
> +        `${req.protocol}` + ":",
я бы здесь первым сделал шаблонную строку по типу `${req.protocol}://${req.headers.host}` и далее

2022-02-20 15:13 UTC, KirillKulakow requested changes
need fix

2022-02-21 08:33 UTC, KirillKulakow approved these changes

2022-02-21 15:04 UTC, merged